# Generated by Django 5.0.1 on 2025-11-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_html',
            field=models.TextField(blank=True, help_text='Full HTML report from CheapCarfax API', null=True),
        ),
    ]
